import { Button } from '@/components/ui/button';
import './globals.css';
import { Inter } from 'next/font/google';
import ThemeToggle from '@/components/ThemeToggle';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body className={`${inter.className}`}>
        <nav className='py-3 border-b'>
          <div className='grid grid-cols-3 items-center  gap-4 container'>
            <Link href={'/'}>
              <h1 className='text-2xl font-semibold font-serif'>Course Tracker</h1>
            </Link>
            <div className='flex justify-center w-full'>
              <Link href={'/'}>
                <Button variant="link">Home</Button>
              </Link>
              <Link href={'/courses'}>
                <Button variant="link">Courses</Button>
              </Link>
              <Link href={'/dashboard'}>
                <Button variant="link">Dashboard</Button>
              </Link>
            </div>
            <ThemeToggle />
          </div>
        </nav>
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
